###登录 login
POST {{host}}/api/system/role/login
Content-Type: application/json

{
  "mobile": "18613030352",
  "password": "123456"
}
> {% client.global.set("token", response.body.data.token); %}


###查询登录日志 queryLoginLogList
GET {{host}}/api/log/login/queryLoginLogList
Authorization: Bearer {{token}}

###查询登录日志 queryLoginLogList
GET {{host}}/api/log/login/queryLoginLogList
Authorization: Bearer {{token}}