// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysUserRoleFieldNames          = builder.RawFieldNames(&SysUserRole{})
	sysUserRoleRows                = strings.Join(sysUserRoleFieldNames, ",")
	sysUserRoleRowsExpectAutoSet   = strings.Join(stringx.Remove(sysUserRoleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysUserRoleRowsWithPlaceHolder = strings.Join(stringx.Remove(sysUserRoleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheHertzdbSysUserRoleIdPrefix = "cache:hertzdb:sysUserRole:id:"
)

type (
	sysUserRoleModel interface {
		Insert(ctx context.Context, data *SysUserRole) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysUserRole, error)
		Update(ctx context.Context, data *SysUserRole) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysUserRoleModel struct {
		sqlc.CachedConn
		table string
	}

	SysUserRole struct {
		Id         int64        `db:"id"`          // 主键
		UserId     int64        `db:"user_id"`     // 用户ID
		RoleId     int64        `db:"role_id"`     // 角色ID
		CreateTime time.Time    `db:"create_time"` // 创建时间
		UpdateTime sql.NullTime `db:"update_time"` // 修改时间
	}
)

func newSysUserRoleModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSysUserRoleModel {
	return &defaultSysUserRoleModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sys_user_role`",
	}
}

func (m *defaultSysUserRoleModel) Delete(ctx context.Context, id int64) error {
	hertzdbSysUserRoleIdKey := fmt.Sprintf("%s%v", cacheHertzdbSysUserRoleIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, hertzdbSysUserRoleIdKey)
	return err
}

func (m *defaultSysUserRoleModel) FindOne(ctx context.Context, id int64) (*SysUserRole, error) {
	hertzdbSysUserRoleIdKey := fmt.Sprintf("%s%v", cacheHertzdbSysUserRoleIdPrefix, id)
	var resp SysUserRole
	err := m.QueryRowCtx(ctx, &resp, hertzdbSysUserRoleIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysUserRoleRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysUserRoleModel) Insert(ctx context.Context, data *SysUserRole) (sql.Result, error) {
	hertzdbSysUserRoleIdKey := fmt.Sprintf("%s%v", cacheHertzdbSysUserRoleIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, sysUserRoleRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.RoleId)
	}, hertzdbSysUserRoleIdKey)
	return ret, err
}

func (m *defaultSysUserRoleModel) Update(ctx context.Context, data *SysUserRole) error {
	hertzdbSysUserRoleIdKey := fmt.Sprintf("%s%v", cacheHertzdbSysUserRoleIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysUserRoleRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.RoleId, data.Id)
	}, hertzdbSysUserRoleIdKey)
	return err
}

func (m *defaultSysUserRoleModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheHertzdbSysUserRoleIdPrefix, primary)
}

func (m *defaultSysUserRoleModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysUserRoleRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysUserRoleModel) tableName() string {
	return m.table
}
